twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        pusher_cluster: '%env(PUSHER_CLUSTER)%'
        pusher_key: '%env(PUSHER_KEY)%'

when@test:
    twig:
        strict_variables: true
